"""create_initial_schema

Revision ID: 1ff57b5fcca1
Revises: 
Create Date: 2026-05-20 11:33:08.094033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff57b5fcca1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', name='adminrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_username'), 'admin_user', ['username'], unique=True)
    op.create_table('poll',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('voting_type', sa.Enum('PLURALITY', 'RANKED', 'RATING', 'YES_NO', name='votingtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', name='pollstatus'), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_status'), 'poll', ['status'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poll_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voter_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poll_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voter_group_token'), 'voter_group', ['token'], unique=True)
    op.create_table('option',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poll_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poll_id', sa.Uuid(), nullable=False),
    sa.Column('voter_group_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('option_id', sa.Uuid(), nullable=False),
    sa.Column('voter_token', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.ForeignKeyConstraint(['voter_group_id'], ['voter_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'voter_group_id', 'voter_token', 'option_id', name='uq_vote_voter_option')
    )
    op.create_index(op.f('ix_vote_voter_token'), 'vote', ['voter_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_voter_token'), table_name='vote')
    op.drop_table('vote')
    op.drop_table('option')
    op.drop_index(op.f('ix_voter_group_token'), table_name='voter_group')
    op.drop_table('voter_group')
    op.drop_table('category')
    op.drop_index(op.f('ix_poll_status'), table_name='poll')
    op.drop_table('poll')
    op.drop_index(op.f('ix_admin_user_username'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
